import { Department, ResourceType, AccessLevel, Resource } from './types';

export const DEPARTMENTS: Department[] = [
  { id: '1', name: 'Electrical Engineering', code: 'EE' },
  { id: '2', name: 'Information Communication Technology', code: 'ICT' },
  { id: '3', name: 'Business & Management', code: 'BUS' },
  { id: '4', name: 'Building & Civil Engineering', code: 'BCE' },
  { id: '5', name: 'Hospitality & Tourism', code: 'HOSP' },
  { id: '6', name: 'Applied Sciences', code: 'AS' },
];

export const RESOURCE_TYPES = Object.values(ResourceType);

export const MOCK_RESOURCES: Resource[] = [
  {
    id: 'res-1',
    title: 'Introduction to Data Structures',
    description: 'Comprehensive lecture notes covering stacks, queues, and linked lists.',
    type: ResourceType.LECTURE_NOTE,
    department: 'Information Communication Technology',
    course: 'Diploma in Computer Science',
    unitCode: 'ICT-201',
    uploaderId: 'lec-1',
    uploadDate: '2024-03-15',
    fileUrl: '#',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=400',
    downloads: 156,
    rating: 4.8,
    accessLevel: AccessLevel.PUBLIC,
    isApproved: true,
  },
  {
    id: 'res-2',
    title: 'Advanced Circuit Analysis (2023 Paper)',
    description: 'Previous year examination paper for Semester 2.',
    type: ResourceType.PAST_PAPER,
    department: 'Electrical Engineering',
    course: 'Diploma in Electrical Engineering',
    unitCode: 'EE-302',
    uploaderId: 'lec-2',
    uploadDate: '2023-11-20',
    fileUrl: '#',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?auto=format&fit=crop&q=80&w=400',
    downloads: 89,
    rating: 4.5,
    accessLevel: AccessLevel.DEPARTMENT_RESTRICTED,
    isApproved: true,
  },
  {
    id: 'res-3',
    title: 'Modern Business Strategies',
    description: 'E-book on management techniques for small to medium enterprises.',
    type: ResourceType.EBOOK,
    department: 'Business & Management',
    course: 'Certificate in Business Management',
    unitCode: 'BUS-105',
    uploaderId: 'lib-1',
    uploadDate: '2024-01-10',
    fileUrl: '#',
    thumbnailUrl: 'https://images.unsplash.com/photo-1454165833767-027ffea9e778?auto=format&fit=crop&q=80&w=400',
    downloads: 230,
    rating: 4.2,
    accessLevel: AccessLevel.PUBLIC,
    isApproved: true,
  },
  {
    id: 'res-4',
    title: 'Building Information Modeling (BIM)',
    description: 'Training video series on BIM implementation in civil engineering.',
    type: ResourceType.VIDEO,
    department: 'Building & Civil Engineering',
    course: 'Diploma in Civil Engineering',
    unitCode: 'BCE-401',
    uploaderId: 'lec-4',
    uploadDate: '2024-02-05',
    fileUrl: '#',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503387762-592dea58ef23?auto=format&fit=crop&q=80&w=400',
    downloads: 342,
    rating: 4.9,
    accessLevel: AccessLevel.PUBLIC,
    isApproved: true,
  }
];